### ISSUE TITLE
Layout is screwed up on Safari

### ISSUE THREAD

**Issue by ejillbaker** [ejbakerart/beadcrochetdesign#11]
The vertical repeat got repositioned out of its area when Susan tried running the code on Safari.  We tried switching her to Chrome and then everything looked fine again.

**Comment by vorth** [comment]
What version of Safari, and what platform?  I'm running 16.5.2 on my Mac, and it works.... 

oops, no I see it now.  Never mind!

**Comment by vorth** [comment]
The issue was happening in all three columns, but it wasn't as obvious in the other two.  Now fixed.
